default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  primary:
    <<: *default
    database: finta-take-home_development
  queue:
    <<: *default
    database: finta-take-home_development_queue
    migrations_paths: db/queue_migrate
test:
  <<: *default
  database: finta-take-home_test

production:
  primary:
    <<: *default
    database: finta-take-home_production
    username: finta_take_home
    password: <%= ENV["FINTA_TAKE_HOME_DATABASE_PASSWORD"] %>
  cache:
    <<: *default
    database: finta-take-home_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: finta-take-home_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: finta-take-home_production_cable
    migrations_paths: db/cable_migrate
